config/routes.rb
Domotic::Application.routes.draw do

  ActionController::Routing::SEPARATORS << '-' unless ActionController::Routing::SEPARATORS.include? '-'

  resources :lamps do
    get 'page-:page', :action => :show_partial, :on => :collection, :as => :page
  end

  resources :rooms do
    get 'page-:page', :action => :show_partial, :on => :collection, :as => :page
  end

  resources :overview, :only => :index

  delete "light-off/:id" => "lights#destroy", :as => :light_off
  post   "light-on/:id"  => "lights#create",  :as => :light_on
end

app/models/lamp.rb
class Lamp < ActiveRecord::Base

  belongs_to :room

  validates :name,       :presence     => true
  validates :house_code, :presence     => true
  validates :unit_code,  :presence     => true
  validates :unit_code,  :numericality => { :only_integer => true, :greater_than => 0, :less_than => 17 }
  validates :house_code, :inclusion    => { :in => Domotic::Data::House_code, :message => I18n.t("activerecord.errors.models.lamp.attributes.house_code.is_not_a_valid_house_code")}

  composed_of :module,
              :class_name => "Cm15::Components::Lamp",
              :mapping => [%w(name name), %w(house_code house_code), %w(unit_code unit_code)]

  self.per_page = 5
end

app/models/room.rb
class Room < ActiveRecord::Base

  has_many :lamps

  validates :name, :presence => true

  self.per_page = 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :active_menu, :active_sub_menu

  def active_menu
    @active_menu ||= self.controller_name.to_sym
  end

  def active_sub_menu
    @active_sub_menu ||= self.action_name.to_sym
  end
end

app/controllers/lamps_controller.rb
class LampsController < ApplicationController

  respond_to :html
  
  expose(:paging_lamps) { Lamp.paginate(:page => params[:page]) }
  expose(:lamp)
  expose(:rooms) { Room.all }

  def show_partial
    render :partial => 'listing_lamps'
  end

  def create
    if lamp.save
      redirect_to lamp, :notice => t('lamps.controller.created')
    else
      @active_sub_menu = :new
      render :action => "new"
    end
  end

  def update
    if lamp.update_attributes(params[:lamp])
      redirect_to lamp, :notice => t('lamps.controller.updated')
    else
      render :action => "edit"
    end
  end

  def destroy
    lamp.destroy
    redirect_to lamps_url
  end
end

app/controllers/lights_controller.rb
class LightsController < ApplicationController

  expose(:lamp)

  def create
    light {|lamp| lamp.module.light_on }
  end

  def destroy
    light {|lamp| lamp.module.light_off }
  end

  private

  def light &block
    block.call lamp
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.text { render :nothing => true, :status => 200 }
    end
  end
end

app/controllers/overview_controller.rb
class OverviewController < ApplicationController

  respond_to :html
  
  expose(:rooms) { Room.all }

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  respond_to :html
  
  expose(:paging_rooms) { Room.paginate(:page => params[:page]) }
  expose(:paging_lamps) { Lamp.paginate(:page => params[:page]) }
  expose(:lamps) { Lamp.all }
  expose(:room)

  def show_partial
    render :partial => 'listing_rooms'
  end

  def create
    if room.save
      redirect_to room, :notice => t('rooms.controller.created')
    else
      @active_sub_menu = :new
      render :action => "new"
    end
  end

  def update
    if room.update_attributes(params[:room])
      redirect_to room, :notice => t('rooms.controller.updated')
    else
      render :action => "edit"
    end
  end

  def destroy
    room.destroy
    redirect_to rooms_url
  end
end

app/helpers/alert_helper.rb
module AlertHelper
  def show_notices message
    return if message.nil?
    capture_haml do 
      haml_tag :div, :class => "alert-message success", "data-alert" => "" do 
        haml_tag :a, "x", :href => "#", :class => "close"
        haml_tag :p, message
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def main_menu
    menu_items = [
      [:overview, t('menu.overview'), overview_index_path],
      [:rooms,    t('menu.rooms'),    rooms_path],
      [:lamps,    t('menu.lamps'),    lamps_path],
    ]
    capture_haml do
      haml_tag :ul, :class => "pills" do
        menu_items.each do |name, label, url|
          css_class = @active_menu == name ? "active" : ""
          haml_tag :li, :class => css_class do
            haml_tag :a, label,:href => url
          end
        end
      end
    end
  end

  def sub_menu items
    capture_haml do
      haml_tag :ul, :class => "tabs" do
        items.each do |name, label, url|
          css_class = name == @active_sub_menu ? "active" : ""
          haml_tag :li, :class => css_class do
            haml_tag :a, label, :href => url
          end
        end
      end
    end
  end
end

app/helpers/lamps_helper.rb
module LampsHelper
  def sub_menu_lamps
    items = [
      [:index, t('submenu.lamps.show_all'),    lamps_path],
      [:new,   t('submenu.lamps.create_lamp'), new_lamp_path],
    ]

    sub_menu items
  end
end

app/helpers/overview_helper.rb
module OverviewHelper

  def sub_menu_overview
    items = [
      [:index, "Installation",    overview_index_path],
    ]

    sub_menu items
  end

  def draw_installation rooms
    printing    = ''
    rooms.each do |room|
      lamps             = room.lamps
      lamps_entity_ids  = lamps.map(&:id).join ','
      lamps_entities    = lamps.map {|lamp| "(#{lamp.id}:{{<a href=\"#{lamp_path lamp}\">#{lamp.name}</a>}})" }.join ' '
      
      if lamps.length == 0
        printing  += "({{<a href=\"#{room_path room}\">#{room.name}</a>}})"
      else
        printing  += "({{<a href=\"#{room_path room}\">#{room.name}</a>}}>[#{lamps_entity_ids}]) || #{lamps_entities}"
      end
      printing += " || "
    end

    capture_haml do 
      haml_tag :pre, printing, :class => 'arrows-and-boxes'
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def sub_menu_rooms
    items = [
      [:index, t('submenu.rooms.show_all'),    rooms_path],
      [:new,   t('submenu.rooms.create_room'), new_room_path],
    ]

    sub_menu items
  end
end

app/views/lamps/_form.html.haml
= form_for lamp do |f|
  
  = f.text_field :name, :placeholder => t('.example.name')

  = f.text_field :house_code, :placeholder => t('.example.house_code')
  
  = f.number_field :unit_code, :placeholder => t('.example.unit_code')
  
  = f.select :room_id, options_for_select(rooms.map { |room|[room.name, room.id] }, lamp.room_id), :include_blank => true
    
  %div.actions
    = f.submit t('views.save'), :class => "btn primary"
    = button_tag t('views.cancel'), :type => "reset", :class => "btn"

app/views/lamps/_listing_lamps.html.haml
= will_paginate paging_lamps, :params => { :controller => :lamps, :action => :show_partial }
%table.bordered-table.zebra-striped
  %tr
    %thead
      %th= t('.name')
      %th= t('.code')
      %th= t('.room')
      %th{:colspan => 2}
      %th{:colspan => 2}
    %tbody
      - paging_lamps.each do |lamp|
        %tr
          %td= lamp.name
          %td= "#{lamp.house_code}#{lamp.unit_code}"
          %td= lamp.room.name unless lamp.room.nil?
          %td= link_to t('views.edit'), edit_lamp_path(lamp), :class => "btn"
          %td= link_to t('views.destroy'), lamp, confirm: t('views.confirmation'), :method => :delete, :class => "btn danger"
          %td= button_to t('views.light_on'),  light_on_path(lamp), :class => "btn success"
          %td= button_to t('views.light_off'), light_off_path(lamp), :method => :delete, :class => "btn danger"

app/views/lamps/edit.html.haml
= content_for :title, t('.title', :name => lamp.name.capitalize)

= sub_menu_lamps

%div.row
  %div.span11= render 'form'
  %div.span5.info
    %p= t('.explain_how_to_light_on_or_off_the_module')
    %p= button_to t('views.light_on'),  light_on_path(lamp), :class => "btn success"
    %p= button_to t('views.light_off'), light_off_path(lamp), :method => :delete, :class => "btn danger"

app/views/lamps/index.html.haml
= content_for :title, t('.title')

= sub_menu_lamps

%div#listing-lamps
  = render 'listing_lamps'

app/views/lamps/new.html.haml
= content_for :title, t('.title')

= sub_menu_lamps

= render 'form'

app/views/lamps/show.html.haml
= content_for :title, "#{lamp.name.capitalize} informations"

= sub_menu_lamps

= show_notices notice

= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title="#{t 'views.title'} #{yield :title}"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %div.container
      %h1 
        Domotic
        %small= "#{yield :title}"

      = main_menu
      
      = yield

app/views/overview/_installation_overview.html.haml
= draw_installation rooms

app/views/overview/index.html.haml
= content_for :title, "Installation overview"

= sub_menu_overview

= render 'installation_overview'

app/views/rooms/_form.html.haml
= form_for room do |f|
  
  = f.text_field :name, :placeholder => t('.example.name')
  
  - if room.persisted?
    %div.clearfix
      =f.label :lamps
      %div.input
        %div#listing-lamps= render "listing_lamps"
  
  %div.actions
    = f.submit t('views.save'), :class => "btn primary"
    = button_tag t('views.cancel'), :type => "reset", :class => "btn"

app/views/rooms/_listing_lamps.html.haml
= will_paginate paging_lamps, :params => { :controller => :lamps, :action => :show_partial }
%table.zebra-striped
  %tr
    %thead
      %th 
      %th= t('.name')
      %th= t('.code')
    %tbody
      - paging_lamps.each do |lamp|
        %tr
          %td.span1
            %div.input
              %div.input-prepend
                - if lamp.room == room
                  %label.add-on.active
                    %input{ :type => 'checkbox', :name => "lamp_#{lamp.id}", :id => "lamp_#{lamp.id}", :checked => 'checked', :url => lamp_path(lamp), :room => room.id }
                - elsif not lamp.room.nil?
                  %label.add-on.already-use
                    %input{ :type => 'checkbox', :name => "lamp_#{lamp.id}", :id => "lamp_#{lamp.id}", :url => lamp_path(lamp), :room => room.id }
                - else
                  %label.add-on
                    %input{ :type => 'checkbox', :name => "lamp_#{lamp.id}", :id => "lamp_#{lamp.id}", :url => lamp_path(lamp), :room => room.id }
          %td
            %label{ :for => "lamp_#{lamp.id}" }= lamp.name
          %td= "#{lamp.house_code}#{lamp.unit_code}"

%div#lamp-already-use-in-another-room.modal.hide.fade
  %div.modal-header
    %a.close{:href => "#"} x
    %h3= t('.popup.title')
  %div.modal-body
    %p= t('.popup.lamp_already_used_in_another_room')
    %p= t('.popup.confirmation')
  %div.modal-footer
    %a.btn.primary{:href => "#"} Yes
    %a.btn.secondary{:href => "#"} No

app/views/rooms/_listing_rooms.html.haml
= will_paginate paging_rooms, :params => { :controller => :rooms, :action => :show_partial }
%table.bordered-table.zebra-striped
  %tr
    %thead
      %th= t('.name')
      %th{:colspan => 2}
    %tbody
      - paging_rooms.each do |room|
        %tr
          %td= room.name
          %td= link_to t('views.edit'), edit_room_path(room), :class => "btn"
          %td= link_to t('views.destroy'), room, confirm: t('views.confirmation'), :method => :delete, :class => "btn danger"
          

app/views/rooms/edit.html.haml
= content_for :title, t('.title', :name => room.name.capitalize)

= sub_menu_rooms

= render 'form'

app/views/rooms/index.html.haml
= content_for :title, t('.title')

= sub_menu_rooms

%div#listing-rooms
  = render 'listing_rooms'

app/views/rooms/new.html.haml
= content_for :title, t('.title')

= sub_menu_rooms

= render 'form'

app/views/rooms/show.html.haml
= content_for :title, "#{room.name.capitalize} informations"

= sub_menu_rooms

= show_notices notice

= render 'form'